version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync
    install:
      - "true"

sphinx:
  configuration: source/conf.py
  builder: dirhtml
