#!/bin/bash
# Run this script to generate the release issue checklist for easy pasting into GitHub

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_NAME=$(basename $SCRIPT_DIR)/$(basename "${BASH_SOURCE[0]}")
cd $SCRIPT_DIR/..

cat << EOF
# Release checklist

For the upcoming release we need to verify our documentation. This is a best efforts activity
so please refer to the checklist from the previous release and focus on pages that were not
verified last time.

## Verify pages

- Look at the nightly build of each page listed below
- Check page renders correctly
- Check for spelling/grammar problems
- Check that the instructions work as expected
- Ensure legacy pages with out of date instructions have a content warning
- If page needs updating convert the task to an issue and open a PR that closes the issue

\`\`\`[tasklist]
### Pages
EOF

find source -type f -name "*.ipynb" -o -name "*.md" \
    | grep -v "_includes" \
    | sed -e "s/^source/- [ ] https\:\/\/docs.rapids.ai\/deployment\/nightly/" \
    | sed -e "s/index.md//" \
    | sed -e "s/.md/\//"\
    | sed -e "s/.ipynb/\//" \
    | sort -u

cat << EOF
\`\`\`

_Issue text generated by \`${SCRIPT_NAME#./}\`._
EOF
